from enum import StrEnum


class LearningState(StrEnum):
    TO_LEARN = "TO_LEARN"
    IN_LEARNING = "IN_LEARNING"
    LEARNING_COMPLETED = "LEARNING_COMPLETED"


class ProofState(StrEnum):
    UNPROVEN = "UNPROVEN"
    EMERGING = "EMERGING"
    DEMONSTRATED = "DEMONSTRATED"
    PROVEN = "PROVEN"


CAPABILITY_CODES = (
    "OWNERSHIP_ACCOUNTABILITY",
    "PROBLEM_FRAMING",
    "DECISION_MAKING",
    "DATA_THINKING",
    "CUSTOMER_UNDERSTANDING",
    "PRODUCT_DISCOVERY",
    "PRODUCT_STRATEGY",
    "PRIORITIZATION",
    "METRICS_EXPERIMENTATION",
    "PRODUCT_ECONOMICS",
    "DELIVERY",
    "STAKEHOLDER_ALIGNMENT",
    "PRODUCT_LEADERSHIP",
    "SYSTEM_BUILDING",
    "REFLECTION_LEARNING",
)
